### PR TITLE
Re-trigger After Failure By Trusted User With Flake Comment With Proper Links

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports failed test
 - [T] reports flake issue
 - [T] re-triggers test
 - [R] re-runs test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/5/
https://github.com/openshift/test-pull-requests-redshirt/issues/12

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/20/
https://github.com/openshift/test-pull-requests-redshirt/issues/12

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
@danmcp bot correctly cares only about one link being valid now

**Comment by stevekuznetsov** [comment]
[failure]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/36/
#12

**Comment by stevekuznetsov** [comment]
[failure] #12

**Comment by stevekuznetsov** [comment]
#12

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
#12

**Comment by dobbymoodge** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@dobbymoodge Sorry - until we figure out a different testing method, can we have our own pulls so I don't get spammed for this PR (since I'm the author I can't seem to unsub)

**Comment by dobbymoodge** [comment]
I hijacked it to test. Sorry for the noise. :D

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
#12

**Comment by dobbymoodge** [comment]
[failure]

**Pull request closed without merging**
