### PR TITLE
Re-trigger After Failure By Trusted User

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports failed test
 - [T] re-triggers test
 - [R] pastes error message, does not trigger test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[test]

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]

**Pull request closed without merging**
