### PR TITLE
Re-trigger After Failure By Trusted User After Update

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports failed test
 - [T] adds commits
 - [T] re-triggers test
 - [R] re-runs test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]

**Pull request closed without merging**
