### PR TITLE
Re-trigger After Failure By Trusted User With Flake Comment Without Jenkins Job Link

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports failed test
 - [T] reports flake issue without Jenkins link
 - [T] re-triggers test
 - [R] pastes error message, does not trigger test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/test-pull-requests-redshirt/issues/12

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://github.com/openshift/test-pull-requests-redshirt/issues/12

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]

**Pull request closed without merging**
