### PR TITLE
Re-trigger After Failure By Trusted User With Flake Comment Without GitHub Issue Link

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports failed test
 - [T] reports flake issue without GitHub issue link
 - [T] re-triggers test
 - [R] pastes error message, does not trigger test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/7/

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/22/

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]

**Comment by stevekuznetsov** [comment]
[failure]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/38/

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/38/

**Comment by dobbymoodge** [comment]
[failure]

**Comment by dobbymoodge** [comment]
[failure]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_redshirt_failure/58/

**Pull request closed without merging**
