### PR TITLE
Re-trigger After Success By Administrator

### PR DESCRIPTION
**Pull request by stevekuznetsov**
- [T] makes a pull request
 - [T] tags for test
 - [R] reports sucessful test
 - [A] re-triggers test
 - [R] doesn't recognize admin as valid re-tagger after success, doesn't re-run test

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[success]

**Comment by danmcp** [comment]
[success]

**Comment by danmcp** [comment]
[success]

**Comment by stevekuznetsov** [comment]
@danmcp you're in too many groups, this tests needs someone that's only in the admin group and not in the other one

**Comment by danmcp** [comment]
@stevekuznetsov We don't have any of those users.

**Comment by stevekuznetsov** [comment]
This is a bad test case for our org then, but technically valid due to the way admins are identified

**Pull request closed without merging**
